parameters:
    champ94.eaglesteam.tables.et_series: '%core.table_prefix%et_series'
    champ94.eaglesteam.tables.et_chapters: '%core.table_prefix%et_chapters'
    champ94.eaglesteam.tables.et_board_images: '%core.table_prefix%et_board_images'